#!/usr/bin/env python3
"""Generate provider-specific adapter files from a canonical SKILL.md.

Each skill ships one canonical SKILL.md (German content, provider-agnostic).
This script reads that file and emits adapters for Claude Code, Gemini Gems,
and OpenAI custom GPTs / Assistants.

Output goes either to `<skill>/providers/<provider>.md` (default) or to a
flat directory specified with `--out`.

Usage:
    python scripts/route_provider.py --provider claude
    python scripts/route_provider.py --provider gemini --skill arbeitsrecht/kuendigungs-pruefung
    python scripts/route_provider.py --provider openai --area arbeitsrecht --out dist/openai
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
AREAS = [
    "arbeitsrecht",
    "datenschutzrecht",
    "vertragsrecht",
    "mietrecht",
    "gesellschaftsrecht",
    "strafrecht",
    "ki-vo-compliance",
    "nis2",
    "hinweisgeberschutz",
    "lieferkettengesetz",
    "dora",
    "dsa-dma",
    "csrd",
    "insolvenzrecht",
    "prozessrecht",
    "it-recht",
    "bankrecht",
    "erbrecht",
    "familienrecht",
    "betreuungsrecht",
    "gewerblicher-rechtsschutz",
    "steuerrecht",
    "verwaltungsrecht",
]

CLAUDE_HEADER = """---
provider: claude-code
source_skill: {skill_path}
---

<!-- AUTO-GENERATED from {skill_path} via scripts/route_provider.py.
     Edit the canonical SKILL.md, not this file. -->

"""

GEMINI_HEADER = """SYSTEM INSTRUCTIONS — Gemini Gem
================================
Source: {skill_path} (canonical SKILL.md)
Generated by scripts/route_provider.py

Paste the following block into the "Instructions" field of a new Gemini Gem.
Then enable Google Search if your skill needs verification fetches; otherwise
leave it disabled to keep outputs reproducible.

----- BEGIN GEM INSTRUCTIONS -----

"""

GEMINI_FOOTER = """
----- END GEM INSTRUCTIONS -----

Reminder: This Gem runs OUTSIDE the § 203 StGB-compliant gateway by default.
For Mandatsarbeit, route via a German gateway (see references/gateway-setup.md).
"""

OPENAI_HEADER = """SYSTEM INSTRUCTIONS — OpenAI Custom GPT / Assistant
==================================================
Source: {skill_path} (canonical SKILL.md)
Generated by scripts/route_provider.py

Custom GPT (chatgpt.com):
  1. Create a GPT -> Configure tab
  2. Paste the block below into "Instructions"
  3. Conversation starters: copy from the "Beispiele" section
  4. Capabilities: enable "Web Browsing" only if your skill requires verification fetches

Assistants API (programmatic):
  client = OpenAI(...)
  assistant = client.beta.assistants.create(
      name="<skill-name>",
      instructions=open("openai.md").read(),
      model="gpt-4o",
  )

----- BEGIN INSTRUCTIONS -----

"""

OPENAI_FOOTER = """
----- END INSTRUCTIONS -----

Reminder: This Assistant runs OUTSIDE the § 203 StGB-compliant gateway by default.
For Mandatsarbeit, route via a German gateway (see references/gateway-setup.md).
"""


def strip_frontmatter(text: str) -> tuple[str, str]:
    if not text.startswith("---"):
        return "", text
    parts = text.split("---", 2)
    if len(parts) < 3:
        return "", text
    return parts[1].strip(), parts[2].lstrip("\n")


def render(provider: str, skill_path: str, frontmatter: str, body: str) -> str:
    if provider == "claude":
        return CLAUDE_HEADER.format(skill_path=skill_path) + body
    if provider == "gemini":
        return GEMINI_HEADER.format(skill_path=skill_path) + body + GEMINI_FOOTER
    if provider == "openai":
        return OPENAI_HEADER.format(skill_path=skill_path) + body + OPENAI_FOOTER
    raise ValueError(f"unknown provider: {provider}")


def find_skills(area: str | None, skill: str | None) -> list[Path]:
    if skill:
        skill_dir = REPO_ROOT / skill
        if not skill_dir.is_dir():
            sys.exit(f"skill directory not found: {skill_dir}")
        return [skill_dir]
    areas = [area] if area else AREAS
    found: list[Path] = []
    for a in areas:
        skills_dir = REPO_ROOT / a / "skills"
        if not skills_dir.is_dir():
            continue
        for p in sorted(skills_dir.iterdir()):
            if p.is_dir() and (p / "SKILL.md").exists():
                found.append(p)
    return found


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate provider adapters from SKILL.md files")
    parser.add_argument("--provider", required=True, choices=("claude", "gemini", "openai"))
    parser.add_argument("--area", help="One area name (default: all areas)")
    parser.add_argument(
        "--skill",
        help="One skill path relative to repo root, e.g. arbeitsrecht/skills/kuendigungs-pruefung",
    )
    parser.add_argument(
        "--out",
        help="Override output directory. Default writes inside each skill's providers/ folder.",
    )
    args = parser.parse_args()

    skills = find_skills(args.area, args.skill)
    if not skills:
        print("No skills found.")
        return 0

    out_dir = Path(args.out).resolve() if args.out else None
    if out_dir:
        out_dir.mkdir(parents=True, exist_ok=True)

    for skill_dir in skills:
        canonical = skill_dir / "SKILL.md"
        text = canonical.read_text(encoding="utf-8")
        frontmatter, body = strip_frontmatter(text)
        rel = canonical.relative_to(REPO_ROOT).as_posix()
        rendered = render(args.provider, rel, frontmatter, body)

        if out_dir:
            slug = skill_dir.name
            target = out_dir / f"{slug}.{args.provider}.md"
        else:
            target = skill_dir / "providers" / f"{args.provider}.md"
            target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(rendered, encoding="utf-8")
        print(f"wrote {target.relative_to(REPO_ROOT)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
